"""Structured Annex IV template data for Conforma-AI."""

from __future__ import annotations

ANNEX_IV_TEMPLATE = [
    {
        "section": "Cover Page",
        "items": ["System name", "Provider name", "Version", "Document date", "Generated by Conforma-AI"],
    },
    {"section": "Table of Contents", "items": ["Generated automatically from the section structure"]},
    {
        "section": "Section 1 General Description",
        "items": [
            "Intended purpose",
            "Provider information",
            "System architecture",
            "Hardware and software requirements",
            "Market form",
        ],
    },
    {
        "section": "Section 2 Intended Purpose and Users",
        "items": [
            "Detailed intended purpose",
            "Intended users",
            "Affected natural persons",
            "Foreseeable misuse",
        ],
    },
    {
        "section": "Section 3 Human Oversight Measures",
        "items": [
            "Capabilities and limitations",
            "Oversight mechanisms implemented",
            "Interpretation of outputs",
        ],
    },
    {
        "section": "Section 4 Input Data Specifications",
        "items": [
            "Training data",
            "Validation data",
            "Test data",
            "Data provenance",
            "Quality controls",
        ],
    },
    {
        "section": "Section 5 Design Specifications",
        "items": ["Architecture", "Key design choices", "Classification rationale"],
    },
    {
        "section": "Section 6 Risk Management System",
        "items": ["Identified risks", "Risk estimation", "Mitigation measures"],
    },
    {
        "section": "Section 7 Validation and Testing",
        "items": [
            "Test methodology",
            "Test datasets",
            "Discriminatory bias testing",
            "Test results",
        ],
    },
    {
        "section": "Section 8 Performance Metrics",
        "items": ["Accuracy", "Robustness", "Cybersecurity", "Trade-offs"],
    },
    {
        "section": "Section 9 Post-Market Monitoring",
        "items": [
            "Monitoring system",
            "Risk reassessment plan",
            "Incident reporting procedure",
        ],
    },
    {
        "section": "Appendix A Compliance Gaps Identified",
        "items": ["List of missing evidence and provider documentation gaps"],
    },
    {
        "section": "Appendix B References",
        "items": ["Regulation EU 2024/1689", "Source repository URL", "Audit ID", "Timestamp"],
    },
]
